k8s_masters:
  hosts:
    # Control nodes
    vm-0.serg.local:
k8s_workers:
  hosts:
    # Worker nodes
    vm-1.serg.local:
    vm-2.serg.local:
    vm-3.serg.local:
    vm-4.serg.local:
k8s_cluster:
  children:
    k8s_masters:
    k8s_workers:
